schemaVersion: 2.2.0
metadata:
  name: morpheus
  version: 1.0.0
variables:
  MORPHEUS_IMAGE: nvcr.io/nvidia/morpheus/morpheus:v24.03.02-runtime
components:
- name: morpheus
  attributes:
    pod-overrides:
      spec:
        serviceAccountName: morpheus-sa
  container:
    image: "{{MORPHEUS_IMAGE}}"
    mountSources: true
    endpoints:
      - exposure: public
        name: debug-port
        protocol: http
        targetPort: 5678

commands:
  - id: pip-install-requirements
    exec:
      commandLine: mamba env update -n morpheus --file ./conda/environments/all_cuda-121_arch-x86_64.yaml && conda update -n base -c conda-forge conda && pip install debugpy
      group:
        kind: build
        isDefault: true
      component: morpheus
  - id: run-app
    exec:
      commandLine: "bash -c while true; do sleep 1000; done"
      workingDir: ${PROJECTS_ROOT}
      component: morpheus
      group:
        kind: run
        isDefault: true

  
