apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-minio
  labels:
    app: milvus
    component: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
      component: minio
  template:
    metadata:
      labels:
        app: milvus
        component: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2023-03-20T20-16-18Z
          command: 
            - "minio"
            - "server" 
            - "/minio_data"
            - "--console-address"
            - ":9001"
          ports:
            - name: api
              protocol: TCP
              containerPort: 9000
            - name: console
              protocol: TCP
              containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              value: admin
            - name: MINIO_ROOT_PASSWORD
              value: admin123!
          # resources:
            # limits:
            #   memory: "150Mi"
            #   cpu: "100m"
            # requests:
            #   memory: "90Mi"
            #   cpu: "10m"
          readinessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 2
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 2
          volumeMounts:
            - name: minio-data
              mountPath: /minio_data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: milvus-minio-data
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-minio
  labels:
    app: milvus
    component: minio
spec:
  ports:
  - name: api
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: console
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: milvus
    component: minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-minio-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi