apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-etcd
  labels:
    app: milvus
    component: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
      component: etcd
  template:
    metadata:
      labels:
        app: milvus
        component: etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.5
          command: 
            - "etcd"
          ports:
            - name: service
              protocol: TCP
              containerPort: 2379
          env:
            - name: ETCD_AUTO_COMPACTION_MODE
              value: revision
            - name: ETCD_AUTO_COMPACTION_RETENTION
              value: "1000"
            - name: ETCD_QUOTA_BACKEND_BYTES
              value: "4294967296"
            - name: ETCD_SNAPSHOT_COUNT
              value: "50000"
            - name: ETCD_LISTEN_CLIENT_URLS
              value: http://0.0.0.0:2379
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: http://127.0.0.1:2379
            - name: ETCD_DATA_DIR
              value: /etcd
          # resources:
          #   limits:
          #     memory: "50Mi"
          #     cpu: "100m"
          #   requests:
          #     memory: "40Mi"
          #     cpu: "6m"
          readinessProbe:
            exec:
              command:
                - etcdctl
                - endpoint
                - health
            initialDelaySeconds: 2
          livenessProbe:
            exec:
              command:
                - etcdctl
                - endpoint
                - health
            initialDelaySeconds: 2
          volumeMounts:
            - name: etcd-data
              mountPath: /etcd
      volumes:
        - name: etcd-data
          persistentVolumeClaim:
            claimName: milvus-etcd-data
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-etcd
  labels:
    app: milvus
    component: etcd
spec:
  ports:
  - name: service
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: milvus
    component: etcd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-etcd-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi