apiVersion: apps/v1
kind: Deployment
metadata:
  name: morpheus
  labels:
    app: morpheus
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: morpheus
  template:
    metadata:
      labels:
        app: morpheus
    spec:
      containers:
        - name: morpheus
          image: image-registry.openshift-image-registry.svc:5000/demo/morpheus:latest
          command: 
            - "/bin/bash"
            - "-c"
            - "--"
          args: [ "while true; do sleep 30; done;" ]
          securityContext:
           runAsUser: 0
      serviceAccountName: morpheus-sa