apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: morpheus-incremental
spec:
  tasks:
    - name: buildah
      params:
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/ruben-nvidia/morpheus:latest'
        - name: BUILDER_IMAGE
          value: 'registry.redhat.io/rhel8/buildah@sha256:b48f410efa0ff8ab0db6ead420a5d8d866d64af846fece5efb185230d7ecf591'
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./docker/Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: docker
        - name: BUILD_EXTRA_ARGS
          value: '--target runtime  --build-arg CUDA_MAJOR_VER=12  --build-arg CUDA_MINOR_VER=1  --build-arg CUDA_REV_VER=1  --build-arg FROM_IMAGE=nvidia/cuda  --build-arg LINUX_DISTRO=ubuntu  --build-arg LINUX_VER=22.04  --build-arg MORPHEUS_ROOT_HOST=.  --build-arg MORPHEUS_SUPPORT_DOCA=OFF  --build-arg PYTHON_VER=3.10 --build-arg VERSION_SUFFIX=runtime'
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - prepare-build
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: morpheus-ws
    - name: prepare-build
      taskSpec:
        metadata: {}
        spec: null
        steps:
          - computeResources: {}
            image: 'image-registry.openshift-image-registry.svc:5000/ruben-nvidia/python-311-git-lfs@sha256:0031ce8dfcf4010426533782b2d499069194e8ec7842762132398e7f15cc4684'
            name: build-pre-steps
            script: |
              cd $(workspaces.source.path)
              find . -mindepth 1 -delete
              git clone -b tekton-build https://github.com/ruromero/Morpheus.git . 
              git config --global --add safe.directory /workspace/source 
              git remote add upstream https://github.com/nv-morpheus/Morpheus.git 
              git fetch upstream 
              ./docker/build_container_release.sh
      workspaces:
        - name: source
          workspace: morpheus-ws
  workspaces:
    - name: morpheus-ws
